### ISSUE TITLE
browse mode is incorrectly shown

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/focusHighlight#13]
When "Enable browse mode on page load" is turned off and a web browser window is focused, FH shows the red rectangle, which incorrectly shows the browse mode is active.

**Comment by nishimotz** [comment]
Since 6.0, isPassThroughMode() defaults to True rather than False, so the behavior regarding this is more consistent than the previous versions.

**Comment by britechguy** [comment]
See the topic:  [Has anyone else noticed a change in the behavior of Focus Highlight?](https://nvda.groups.io/g/nvda/topic/has_anyone_else_noticed_a/31822109?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,31822109) on the NVDA group on Groups.io.

I am now having very weird behavior where Focus Highlight appears to be "stuck in focus mode" when browse mode should be available.  File Explorer being the best example of this.   I am shown in focus mode when traversing the list of files and folders, but am not actively renaming one.   Also, and I do not know if this is related, when I am trying to do selection of multiple files using CTRL+Spacebar to get individual files the "unselected" state is announced correctly when I land on it, but hitting spacebar announces "space" rather than "selected."
--

**Comment by nishimotz** [comment]
The first thing is an intentional change in 6.0.
"Enable browse mode on page load" option will be added in NVDA 2019.2.
With this option turned off, and a web browser is just activated, Focus Highlight should show the blue rectangle, rather than the red box.

An app which does not support browse mode is always "passthrough mode," which corresponds to the focus mode.
When browse mode is turned off, a web browser app is in passthrough mode internally as well.
In the previous versions of Focus Highlight did not consistently handle the passthrough mode.

The second thing you mentioned seems not related to this add-on.

**Comment by nishimotz** [comment]
Version 6.1 is out.
https://github.com/nvdajp/focusHighlight/releases/tag/6.1

If you are not comfortable with this issue, please use NVDA Settings dialog Focus Highlight category and turn off "Make focus mode the default" option.
